###### YOUR PROPERTIES HERE ######
guid: 'CHANGEME'
vcenter_password: 'CHANGEME'
ocp4_pull_secret: 'CHANGEME'
##################################

## Defaults
ocp_version: 4.13.18
student_name: lab-user

vcenter_domain: infra.demo.redhat.com
vcenter_hostname: vcsnsx-vc.infra.demo.redhat.com
vcenter_username: sandbox-kw2c5@demo
